### ISSUE TITLE
namespace message data objects

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-messaging#5]
the requestHandler for the messaging service in a WindowIframeDestination will receive ALL messages received by the window using the postMessage api. These could come from other applications.

We should namespace our message data objects and check that first before trying to do anything with a message.

I'm not sure if there are best practices for this. The React Dev Tools, which exposed this bug, use a "source" property that they set to "react-devtools-detector".

Maybe we could use the same "source" property and set it to "alpheios-messaging"? 

This can be reproduced using the treebank-template code at https://github.com/perseids-publications/treebank-template/commit/51a654586f64370c62d9170eb7af30f44afb5e33 with the react dev tools extension installed.

**Comment by kirlat** [comment]
We already have a `Message.type` field that is set to "Generic' and is not used much now. The idea behind it was that we can have different message types such as CEDICT request, Arethusa request, and so on and this field will be used to distinguish between them.

What if we make all those types unique to Alphieos (rename `Generic` to `AlpheiosMessage` and have `AlpheiosCEDICTRequest` and like that) and have a function that will check if type field is present and if its value is of Alpheios type (i.e. whether the message type is among `Message.types` constants)? That should be really simple and will not require an additional field. It will also make a currently unused `type` field to serve a good cause. What do you think?

**Comment by balmas** [comment]
That seems ok. I don't know if there are any best practices around namespacing such messages, or if the API is too new for them to have evolved.

**Comment by balmas** [comment]
@kirlat can this one be closed now?

**Comment by kirlat** [comment]
Yes, it has been completed.

**Comment by balmas** [comment]
the requestHandler is still throwing an error on the messages posted from the React Dev tools, so I don't think this one is fully fixed.

this code is the problem:

```
_requestHandler (callbackFn, event) {
    // `data` prop of an event contains a request message object
    let request = event.data // eslint-disable-line prefer-const
    request.header.origin = event.origin
    callbackFn(request, this.sendResponse.bind(this))
  }
```

The request coming from the React Dev Tools doesn't have a header property. So we should have checked to see if this is a message we understand before this point.

**Comment by kirlat** [comment]
The changes that has been merged to master should take care of that

**Comment by balmas** [comment]
verified that we no longer get an error when using the treebank code with react dev tools enabled.
